name: filmguru
description: Netguru Flutter recrutation app
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  equatable: ^1.1.1
  json_annotation: ^3.0.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  build_runner: ^1.0.0
  build_test: ^0.10.3
  mockito: ^4.1.1
  bloc_test: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json
