name: filmguru
description: Netguru Flutter recrutation app
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^7.0.1
  bloc: ^7.0.0
  equatable: ^2.0.2
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  freezed_annotation: ^0.14.2
  dartz: ^0.9.2
  rxdart: ^0.27.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^4.1.3
  build_runner: ^2.0.4
  build_test: ^2.1.0
  mockito: ^5.0.10
  bloc_test: ^8.0.2
  freezed: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/mock/movies_response.json

flutter_intl:
  enabled: true
